service: backend
disabledDeprecations: "*"
configValidationMode: error
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 256

plugins:
  - serverless-offline
  - serverless-bundle

package:
  individually: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
    environment:
      STUDREVIEWS_DB_URI: mongodb+srv://SCEbeersheva:12345@cluster0.ursrw.mongodb.net/students?retryWrites=true&w=majority
      STUDREVIEWS_NS: students
      JWT: 33033a5e13fe45e6964bd1c6ed0023c7717cc62fb535c8e6d8f049c77819631d
      PORT: 5000
      NODE_ENV: production
